[application]

# dioxus project name
name = "wept"

# default platform
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

# hot reload by default
hot_reload = true

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "W/ept | A headless Dioxus client for WordPress"

[web.watcher]

index_on_404 = true

watch_path = ["src", "examples"]

[bundler]
# Bundle identifier
identifier = "wept.coded.cc"

# Bundle publisher
publisher = "wept"

# Bundle short description
short_description = "A headless Dioxus client for WordPress"

# Bundle long description
long_description = """
A headless Dioxus client for WordPress
"""

# Bundle icon
# icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = "MIT"

# Bundle category
category = "Utility"
