[application]

# dioxus project name
name = "wept"

# default platform
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

# hot reload by default
hot_reload = true

[web.app]

# HTML title tag content
title = "W/ept | A headless Dioxus client for WordPress"

[web.watcher]

index_on_404 = true

watch_path = ["src", "examples"]
